// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzwBJxAgWrlb3va8gCFOr1-asPZQ-iGAo',
    appId: '1:448223279941:web:a2c848ed32c1f328f65c2c',
    messagingSenderId: '448223279941',
    projectId: 'ecycle-app2',
    authDomain: 'ecycle-app2.firebaseapp.com',
    storageBucket: 'ecycle-app2.firebasestorage.app',
    measurementId: 'G-DXJD1VYQGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Ev6HGnpKzYrTGn82mwP_m3bKEL6zgsU',
    appId: '1:448223279941:android:dcb2f575a05efe18f65c2c',
    messagingSenderId: '448223279941',
    projectId: 'ecycle-app2',
    storageBucket: 'ecycle-app2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCdoFmewBmD3pq5yZCXh1hvsm_DihyiC4',
    appId: '1:448223279941:ios:eb9396e6d6759384f65c2c',
    messagingSenderId: '448223279941',
    projectId: 'ecycle-app2',
    storageBucket: 'ecycle-app2.firebasestorage.app',
    iosClientId: '448223279941-j9b56tc64jvvbd5fsv8f2kfqm8lg3fkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCdoFmewBmD3pq5yZCXh1hvsm_DihyiC4',
    appId: '1:448223279941:ios:eb9396e6d6759384f65c2c',
    messagingSenderId: '448223279941',
    projectId: 'ecycle-app2',
    storageBucket: 'ecycle-app2.firebasestorage.app',
    iosClientId: '448223279941-j9b56tc64jvvbd5fsv8f2kfqm8lg3fkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzwBJxAgWrlb3va8gCFOr1-asPZQ-iGAo',
    appId: '1:448223279941:web:4be570a834dbc148f65c2c',
    messagingSenderId: '448223279941',
    projectId: 'ecycle-app2',
    authDomain: 'ecycle-app2.firebaseapp.com',
    storageBucket: 'ecycle-app2.firebasestorage.app',
    measurementId: 'G-603GHH7K6H',
  );

}