// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANqH-1Tmh19F83iok_zBNh0KsRrIRuiQQ',
    appId: '1:971618052811:web:1995e410320b3b01e0894e',
    messagingSenderId: '971618052811',
    projectId: 'e-cycle3-cf4eb',
    authDomain: 'e-cycle3-cf4eb.firebaseapp.com',
    storageBucket: 'e-cycle3-cf4eb.firebasestorage.app',
    measurementId: 'G-TQ3EV1CSNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCyfNd83-fhfdrLpXK1EUWseZms4lyjno',
    appId: '1:971618052811:android:006f803a8ff22016e0894e',
    messagingSenderId: '971618052811',
    projectId: 'e-cycle3-cf4eb',
    storageBucket: 'e-cycle3-cf4eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW4cAB_-U28CX8baHsqUH8xKtxYC7me08',
    appId: '1:971618052811:ios:4261b33222161666e0894e',
    messagingSenderId: '971618052811',
    projectId: 'e-cycle3-cf4eb',
    storageBucket: 'e-cycle3-cf4eb.firebasestorage.app',
    androidClientId: '971618052811-b1g2tavcp84u93s35akuqn8nbe4d0h0j.apps.googleusercontent.com',
    iosClientId: '971618052811-2clocg1aui2s49j4i8og07s8l4tn7qnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW4cAB_-U28CX8baHsqUH8xKtxYC7me08',
    appId: '1:971618052811:ios:4261b33222161666e0894e',
    messagingSenderId: '971618052811',
    projectId: 'e-cycle3-cf4eb',
    storageBucket: 'e-cycle3-cf4eb.firebasestorage.app',
    androidClientId: '971618052811-b1g2tavcp84u93s35akuqn8nbe4d0h0j.apps.googleusercontent.com',
    iosClientId: '971618052811-2clocg1aui2s49j4i8og07s8l4tn7qnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANqH-1Tmh19F83iok_zBNh0KsRrIRuiQQ',
    appId: '1:971618052811:web:86ee6cae5f424ca9e0894e',
    messagingSenderId: '971618052811',
    projectId: 'e-cycle3-cf4eb',
    authDomain: 'e-cycle3-cf4eb.firebaseapp.com',
    storageBucket: 'e-cycle3-cf4eb.firebasestorage.app',
    measurementId: 'G-CBQSD94R9T',
  );
}
